# Path related
dataset_raw_path: data/raw/ufc-master.csv
dataset_cleaned_path: data/processed/ufc_cleaned.pkl
csv_for_eda_path: data/processed/ufc_eda.csv
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_set_modelready_path:
- data/processed/x_train_modelready.pkl
- data/processed/y_train_modelready.pkl
valid_set_modelready_path:
- data/processed/x_valid_modelready.pkl
- data/processed/y_valid_modelready.pkl
test_set_modelready_path:
- data/processed/x_test_modelready.pkl
- data/processed/y_test_modelready.pkl
production_model_path: models/production_model.pkl
label_encoder_path: models/preprocessor/label_encoder.pkl
ordinal_encoder_path:
- models/preprocessor/oe_predefined.pkl
- models/preprocessor/oe_auto.pkl
imputer_path: models/preprocessor/imputer.pkl
scaler_path: models/preprocessor/scaler.pkl
pca_path: models/preprocessor/pca/pca.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# Predictors and label related
target: Winner
predictors:
- R_odds
- B_odds
- R_ev
- B_ev
- gender
- B_current_lose_streak
- B_avg_TD_pct
- R_avg_SIG_STR_pct
- R_win_by_Decision_Majority
- R_win_by_Decision_Unanimous
- avg_sub_att_dif
- avg_td_dif
- R_Women's Strawweight_rank
- R_Welterweight_rank
- B_Bantamweight_rank
- r_dec_odds
- b_dec_odds
- b_sub_odds
- r_ko_odds
- b_ko_odds

# Splitting related
test_size: 0.3 # test+valid ratio to whole dataset
valid_size: 0.5 # valid ratio to test+valid 

# EDA in tableau
eda_in_tableau_path:
- assets/eda_in_tableau/Sheet 1.png
- assets/eda_in_tableau/Sheet 2 (1).png
- assets/eda_in_tableau/Sheet 2 (2).png
- assets/eda_in_tableau/Sheet 2 (3).png
- assets/eda_in_tableau/Sheet 2 (4).png
- assets/eda_in_tableau/Sheet 2 (5).png
- assets/eda_in_tableau/Sheet 2 (6).png
- assets/eda_in_tableau/Sheet 2 (7).png
- assets/eda_in_tableau/Sheet 2 (8).png
- assets/eda_in_tableau/Sheet 2 (9).png
- assets/eda_in_tableau/Sheet 2 (10).png
- assets/eda_in_tableau/Sheet 2 (11).png
- assets/eda_in_tableau/Sheet 2 (12).png
